name: Workflow1.1
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download project code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  Test:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Download project code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci      
      - name: Run test
        run: npm run test
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Download project code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci      
      - name: run build
        run: npm run build
      - name: output message
        run: echo "Workflow Running"
